apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: layer-00-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/thfx31/Ynov_k8s.git'
    targetRevision: feat/gitops
    path: k8s/00-infra
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration  