apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: layer-01-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/thfx31/Ynov_k8s.git'
    targetRevision: feat/gitops
    path: k8s/01-initialisation
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 