apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0aGZ4MzEiLCJwYXNzd29yZCI6ImRja3JfcGF0X3ltS3pLMThpWTJuUHZ6Um5ySlI2Y2ZrQmxqYyIsImF1dGgiOiJkR2htZURNeE9tUmphM0pmY0dGMFgzbHRTM3BMTVRocFdUSnVVSFo2VW01eVNsSTJZMlpyUW14cVl3PT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2025-12-11T13:33:19Z"
  name: dockerhub-secret
  namespace: rt
  resourceVersion: "74466"
  uid: a25e5565-8d16-4234-a2d6-a46063c0aadd
type: kubernetes.io/dockerconfigjson
